name: Deploy Streamlit (Pole Pipeline) to Cloud Run

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet

      - name: Build & Push image (Cloud Build)
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/pole-streamlit:latest

      - name: Deploy to Cloud Run (CPU)
        run: |
          gcloud run deploy pole-streamlit \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/pole-streamlit:latest \
            --region=${{ secrets.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --cpu=4 --memory=8Gi \
            --port=8501
